import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv('Chocolate Sales.csv')

null_num = data.isna().sum()
print(null_num)

data['Amount'] = (data['Amount'].str.replace(r'[\$,"]','',regex=True)
                  .astype(int))
data['Date'] = pd.to_datetime(data['Date'], format = '%d-%b-%y')

sort_by_date = data.sort_values(by='Date')
group_by_date = sort_by_date.groupby(data['Date'].dt.to_period('M'))['Amount'].agg(['sum'])

DataDesc = data[['Amount', 'Boxes Shipped']].describe()
print('==============================\n')
print('Data Statistics')
print(DataDesc)
print('==============================\n')

amount_IQR = data['Amount'].quantile(0.75) - data['Amount'].quantile(0.25)
boxes_shipped_IQR = data['Boxes Shipped'].quantile(0.75) - data['Boxes Shipped'].quantile(0.25)
amount_outlier = data['Amount'].quantile(0.75) + 1.5 * amount_IQR
boxes_shipped_outlier = data['Boxes Shipped'].quantile(0.75) + 1.5 * boxes_shipped_IQR
print('Upper Outlier for Transaction Amount:', amount_outlier)
print('Upper Outlier for Boxes Shipped:', boxes_shipped_outlier)

group_by_person = data.groupby('Sales Person')['Amount'].agg(['sum'])
sorted_group_by_person = group_by_person.sort_values(by = 'sum')
print('==============================\n')
print('Total Transaction Amount Generated by Each Sales Representative:')
print(sorted_group_by_person)

group_by_product = data.groupby('Product')['Amount'].agg(['sum'])
sorted_group_by_product = group_by_product.sort_values(by = 'sum')
print('==============================\n')
print('Total Transaction Amount Generated by Each Product:')
print(sorted_group_by_product)

print('==============================\n')
print('Correlation Between Boxes Shipped and Transaction' \
' Amount of Each Product:')
product_correlation = (data.groupby('Product')[['Amount','Boxes Shipped']]
                       .corr().unstack()['Amount']['Boxes Shipped'])
print(product_correlation)

print('==============================\n')
group_by_country = data.groupby('Country')['Boxes Shipped'].agg(['sum'])
sorted_group_by_country = group_by_country.sort_values(by = 'sum')

plt.figure(figsize = (7,5))
plt.boxplot(data['Boxes Shipped'])
plt.xlabel('Column')
plt.ylabel('Number of Boxes Shipped')
plt.show()

plt.figure(figsize = (7,5))
plt.boxplot(data['Amount'])
plt.xlabel('Column')
plt.ylabel('Transaction Amount')
plt.show()

plt.figure(figsize = (10,5))
plt.barh(sorted_group_by_person.index, sorted_group_by_person['sum']
         , color='blue')
plt.xlabel('Total Transaction Amount in $')
plt.ylabel('Sales Representative')
plt.yticks(fontsize = 6)
plt.xticks(fontsize = 6)
plt.title('Transaction Amount by Rep')
plt.show()

plt.figure(figsize = (10,5))
plt.barh(sorted_group_by_product.index, sorted_group_by_product['sum']
         , color='skyblue')
plt.xlabel('Total Transaction Amount in $')
plt.ylabel('Product')
plt.yticks(fontsize = 6)
plt.xticks(fontsize = 6)
plt.title('Transaction Amount by Product')
plt.show()

plt.figure(figsize = (5,5))
plt.pie(sorted_group_by_country['sum'], labels = sorted_group_by_country.index,
         autopct='%1.1f%%' )
plt.title('Boxes Shipped by Country')
plt.show()

plt.figure(figsize = (10,5))
plt.bar(group_by_date.index.astype(str), group_by_date['sum'],
         color='skyblue')
plt.plot(group_by_date.index.astype(str), group_by_date['sum'],
          color='red', linewidth = 1)
plt.xlabel('Month')
plt.ylabel('Total Transaction Amount in $')
plt.yticks(fontsize = 6)
plt.xticks(fontsize = 6)
plt.title('Transaction Amount by Month')
plt.show()
